### ISSUE TITLE
Lose bold styling on transformed message after switching levels

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [ScottLogic/prompt-injection#752] opened 2024-01-09 14:46 UTC
# Bug report

## Description

Transformed message should show original message in bold like:
![image](https://github.com/ScottLogic/prompt-injection/assets/118981273/88ea62c1-5f13-4f6a-972b-9f83dc541c51)

However after switching level, the bold effect is lost
![image](https://github.com/ScottLogic/prompt-injection/assets/118981273/e1d87773-cc0b-4fc0-b5fa-662d143cdc7a)

## Reproduction steps

1. activate XML tagging
2. send a message
3. see original message in bold
4. switch level then back 
5. see bold effect is gone

## Expected behaviour

Bold style persists when changing level 

## Software (please complete the following information):

- Browser: [e.g. chrome, safari]

## Acceptance criteria

**GIVEN** some setup
**WHEN** an action happens
**THEN** the expected outcome

**Comment by gsproston-scottlogic** [comment] 2024-01-09 15:23
Duplicate of #741

**Closed** 2024-01-15 16:13 UTC
Labels: bug, triage
